version: "3"
services:
  archentsportal:
    image: ithelpdesk
    ports:
      - "8002:8002"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    hostname: ithelpdesk
    environment:
    - EMAIL_USRNAME=nagaraju.boda@archents.com
    volumes:
      - /usr/app/node_modules
      - /home/nagaraju/ArchentsItHelpDesk/complaint-Portal:/usr/app
    networks:
      teleext:
        aliases:
          - ithelpdesk
networks:
  teleext:
    external:
      name: teleext